FROM jlphillips/csci4850:2021-10-15-gpu

LABEL maintainer="Joshua L. Phillips <https://www.cs.mtsu.edu/~jphillips/>"

# Build date: triggers cache rebuild
ENV COMPBIO_BUILD_DATE 2021-10-15

# Install as user
USER $NB_UID

# Qiime2
RUN wget https://data.qiime2.org/distro/core/qiime2-2021.4-py38-linux-conda.yml && \
    mamba env create -n qiime2-2021.4 --file qiime2-2021.4-py38-linux-conda.yml  && \
    rm qiime2-2021.4-py38-linux-conda.yml
SHELL ["mamba", "run", "-n", "qiime2-2021.4", "/bin/bash", "-o", "pipefail", "-c"]
RUN python -m ipykernel install --name qiime2-2021.4 --prefix /opt/conda --display-name "Python 3 (Qiime2)"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Dada2
RUN R -e "install.packages('BiocManager',dependencies=TRUE, repos='http://cran.rstudio.com/')" && \
    R -e "BiocManager::install('dada2')" 

# Other tools... (some should probably be merged above instead)
RUN R -e "BiocManager::install('phyloseq')"

# Replace PyTorch (CPU with Cuda 11.1)
# RUN pip uninstall -y \
#     torch \
#     torchvision \
#     torchaudio && \
#     pip install --quiet --no-cache-dir \
#     torch==1.8.2+cu111 \
#     torchvision==0.9.2+cu111 \
#     torchaudio==0.8.2 \
#     -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html && \
#     fix-permissions "${CONDA_DIR}" && \
#     fix-permissions "/home/${NB_USER}"


# Cleanup - not very thorough... needs revision
# RUN mamba clean --all -f -y && \
RUN fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}" && \
    rm -rf .npm .cache/yarn
